version: "3.6"
services:
    # database
    postgres:
      image: postgres:alpine
      container_name: default-postgres
      volumes:
        - ./docker/data/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=default
      ports:
       - "54321:5432"

    redis:
      image: redis:4.0-alpine
      container_name: default-redis
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      ports:
        - '6378:6379'
      command: >
        --requirepass secret

    # The php api webserver
    nginx-api:
      container_name: default-nginx-api
      image: nginx:alpine
      working_dir: /var/www
      volumes:
         - ./api:/var/www
         - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf
      ports:
      - "8000:80"

    # The php api runtime
    phpfpm-api:
      container_name: default-phpfpm-api
      build: ./docker/phpfpm
      image: phpfpm
      environment:
       PHP_IDE_CONFIG: serverName=phpfpm
       XDEBUG_CONFIG: idekey=PHPSTORM
      working_dir: /var/www
      volumes:
       - ./api:/var/www

    # The php admin webserver
    nginx-admin:
     container_name: default-nginx-admin
     image: nginx:alpine
     depends_on: [phpfpm-admin]
     working_dir: /var/www
     volumes:
        - ./api:/var/www
        - ./docker/nginx/admin.conf:/etc/nginx/conf.d/default.conf
     ports:
     - "8001:80"

    # The php admin runtime
    phpfpm-admin:
      build: ./docker/admin
      container_name: default-phpfpm-admin
      depends_on: [redis, postgres]
      environment:
        LARAVEL_HORIZON: "true"
      volumes:
       - ./api:/var/www
